:experimental:
:upkey: &#8593;
:downkey: &#8595;
== help

Para usar o `comando + help` ou parecido irá depender do tipo de comando
que quer utilizar junto com o help. Cada tipo de comando tem uma sintaxe
diferente:


.Bultin do shell
* `help + comando`

.Programas externos ao shell
* `comando --help` (mais usado)
* `comando -h`
* `comando -?`

== man

O man(ual) online está presente na maioria dos comandos.

*man comando* -> exibe um manual com informações do comando.

*man man* -> manual do man.

*man -k palavraChave* -> faz uma busca pela palavraChave em todos os
presentes manuais do sistema.

=== Atalhos de Navegação Dentro do man

[cols="1a,2"]
|===
| Atalho | Propósito 

|kbd:[{upkey}] 
| Navega para linha de cima.

|kbd:[{downkey}]
|navega para linha de baixo

|kbd:[/]

.Atalhos de Navegação da Pesquisa 
!===
!Atalho ! Propósito

!kbd:[N] 
!Próxima incidência

!kbd:[Shift + N]
!Incidência anterior

!===
|pesquisar

|===

== Onde Encontrar Documentação

Para saber o local (diretórios) em que está o(s) manual(ais) de uma
comando usar: `whereis comando`

Depois procure arquivos que teham nomes que fazem referência a
documentação de manuais.

== Onde o man Encontra a Documentação

ver $MANPATH

Se a variável $MANPATH é vazia ele procura um arquivo de configuração e
este arquivo está em `less /etc/manpath.config` . No /etc/manpath.config o
man encontra instruções de como encontrar os manuais dos comandos.

Existe um comando que mostra, de forma resumida, onde o man deve
procurar os manuais:
----
~$ manpath
/usr/local/man:/usr/local/share/man:/usr/share/man
----